#!/bin/bash
# Quick viewer script for Figure 4.6 outputs

OUTPUT_DIR="outputs/exp446_qualitative"

echo "Figure 4.6 - Baseline vs. Method Qualitative Comparison"
echo "========================================================="
echo ""
echo "Available visualizations:"
echo ""
echo "1. 2D Matplotlib Comparisons (PNG images):"
echo "   - $OUTPUT_DIR/figure_4_6_scene0000_00.png (1.2 MB)"
echo "   - $OUTPUT_DIR/figure_4_6_scene0013_02.png (648 KB)"
echo ""
echo "   View with: open/display/eog/feh (your preferred image viewer)"
echo ""
echo "2. Interactive 3D Visualizations (Rerun recordings):"
echo "   - $OUTPUT_DIR/rerun_scene0000_00.rrd (5.4 MB)"  
echo "   - $OUTPUT_DIR/rerun_scene0013_02.rrd (1.2 MB)"
echo ""
echo "   View with:"
echo "   $ rerun $OUTPUT_DIR/rerun_scene0000_00.rrd"
echo "   $ rerun $OUTPUT_DIR/rerun_scene0013_02.rrd"
echo ""
echo "   Or open both at once:"
echo "   $ rerun $OUTPUT_DIR/*.rrd"
echo ""
echo "Summary:"
echo "--------"
echo "Total files generated: 8"
echo "Total size: 8.9 MB"
echo ""
echo "Scene 0000_00: 63 predictions each (dense scene)"
echo "Scene 0013_02: 7 predictions each (sparse scene)"
echo ""
echo "Red/dashed boxes = baseline (rough AABB)"
echo "Blue boxes = method (refined OBB)"
echo "RGB axes = per-box coordinate frames (X=red, Y=green, Z=blue)"
echo ""
echo "For thesis integration:"
echo "- Use PNG images for paper figures"
echo "- Use Rerun for interactive supplementary materials"
echo "- See README.md for detailed documentation"
